# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r1rUBNwtxSbSDHK39WV4hofE2x13EVZ5
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data=pd.DataFrame(np.random.rand(10,10))
plt.figure(figsize=(8,6))
plt.contour(data.values)
plt.show()

